# EYIF Wi-Fi Portal — MikroTik RADIUS setup
#
# Generated by Admin -> RADIUS -> "Download router config".
# Paste into the router terminal, or upload and run: /import file=eyif-radius.rsc
#
# Verify BOTH profile names first — they are separate objects:
#   /ip hotspot profile print        (server profile, default "hsprof1")
#   /ip hotspot user profile print   (user profile, default "default")

:put "EYIF: configuring RADIUS -> __VPS_IP__"

# 1) Point the router at our RADIUS daemon.
:if ([:len [/radius find where address=__VPS_IP__]] = 0) do={
  /radius add service=hotspot address=__VPS_IP__ secret="__RADIUS_SECRET__" \
    authentication-port=__AUTH_PORT__ accounting-port=__ACCT_PORT__ timeout=3s
  :put "  + RADIUS server added"
} else={
  /radius set [find where address=__VPS_IP__] service=hotspot \
    secret="__RADIUS_SECRET__" authentication-port=__AUTH_PORT__ \
    accounting-port=__ACCT_PORT__ timeout=3s
  :put "  ~ RADIUS server updated"
}

# 2) Tell the hotspot profile to authenticate via RADIUS.
# Accounting is ON: the daemon listens on the accounting port and records what
# each code transfers, which is what makes the data limit work. If you turn it
# off, usage stays at zero and the data limit silently never fires.
#
# radius-interim-update is just as important. Without an interim interval the
# router reports only at session end, so nothing lands while a session is live:
# the Data column in Raffle Entries would stay at zero all event, and a lost
# Acct-Stop (or a router reboot) would drop that session's usage entirely.
/ip hotspot profile set [find name=__HS_PROFILE__] use-radius=yes \
  radius-accounting=yes radius-interim-update=5m login-by=http-chap,http-pap
:put "  ~ hotspot profile __HS_PROFILE__ set to use RADIUS (accounting on)"

# 2b) One code = one device at a time. This replaces the Simultaneous-Use := 1
# check the old FreeRADIUS radcheck table enforced; without RADIUS accounting
# our daemon cannot see concurrent sessions, so the router must cap them.
#
# NOTE the different token. "/ip hotspot profile" (above) and
# "/ip hotspot user profile" (below) are two DIFFERENT RouterOS namespaces with
# two different objects and two different default names: the server profile is
# conventionally "hsprof1", the user profile is conventionally "default".
# Using the server-profile name here would match nothing and RouterOS would
# silently do nothing — leaving the concurrency cap unapplied. That is exactly
# why this line has its own token.
/ip hotspot user profile set [find name=__HS_USER_PROFILE__] shared-users=1
:put "  ~ user profile __HS_USER_PROFILE__ limited to 1 device per code"

# 3) Walled garden: let unauthenticated devices reach the portal only.
:if ([:len [/ip hotspot walled-garden find where dst-host="__PORTAL_HOST__"]] = 0) do={
  /ip hotspot walled-garden add dst-host="__PORTAL_HOST__" action=allow
  :put "  + walled-garden entry added for __PORTAL_HOST__"
}

:put "EYIF: done. Check /radius print and /ip hotspot profile print"
