# EYIF Wi-Fi Portal — MikroTik RADIUS setup
#
# Generated by Admin -> RADIUS -> "Download router config".
# Paste into the router terminal, or upload and run: /import file=eyif-radius.rsc
#
# Verify your hotspot profile name first with: /ip hotspot profile print

:put "EYIF: configuring RADIUS -> __VPS_IP__"

# 1) Point the router at our RADIUS daemon.
:if ([:len [/radius find where address=__VPS_IP__]] = 0) do={
  /radius add service=hotspot address=__VPS_IP__ secret="__RADIUS_SECRET__" \
    authentication-port=__AUTH_PORT__ accounting-port=1813 timeout=3s
  :put "  + RADIUS server added"
} else={
  /radius set [find where address=__VPS_IP__] service=hotspot \
    secret="__RADIUS_SECRET__" authentication-port=__AUTH_PORT__ \
    accounting-port=1813 timeout=3s
  :put "  ~ RADIUS server updated"
}

# 2) Tell the hotspot profile to authenticate via RADIUS.
/ip hotspot profile set [find name=__HS_PROFILE__] use-radius=yes \
  login-by=http-chap,http-pap
:put "  ~ hotspot profile __HS_PROFILE__ set to use RADIUS"

# 2b) One code = one device at a time. This replaces the Simultaneous-Use := 1
# check the old FreeRADIUS radcheck table enforced; without RADIUS accounting
# our daemon cannot see concurrent sessions, so the router must cap them.
/ip hotspot user profile set [find name=__HS_PROFILE__] shared-users=1
:put "  ~ user profile __HS_PROFILE__ limited to 1 device per code"

# 3) Walled garden: let unauthenticated devices reach the portal only.
:if ([:len [/ip hotspot walled-garden find where dst-host="__PORTAL_HOST__"]] = 0) do={
  /ip hotspot walled-garden add dst-host="__PORTAL_HOST__" action=allow
  :put "  + walled-garden entry added for __PORTAL_HOST__"
}

:put "EYIF: done. Check /radius print and /ip hotspot profile print"
